### ISSUE TITLE
what's the enity recognition generate speed ?

### ISSUE THREAD

**Issue by feng-1985** [tricktreat/DiffusionNER#1]

**Comment by tricktreat** [comment]
As shown in Table 3 in the [paper](https://arxiv.org/pdf/2305.13298.pdf), we compare the generation efficiency of several generative NER models. When running on a single GeForce RTX 3090, the DiffusionNER model, using a denoising timestep of 1, demonstrated an impressive entity generation rate of ~80 sentences per second.
