### ISSUE TITLE
一直显示Need 1 GPU for Normal Training, All are busy. Waiting for Free GPU ......，应该怎么解决啊

### ISSUE THREAD

**Issue by 3066768977** [tricktreat/DiffusionNER#10]
<img width="755" alt="屏幕截图 2023-09-23 164458" src="https://github.com/tricktreat/DiffusionNER/assets/101509109/ce560547-0d25-4104-b9e9-56966508e204">

一直显示Need 1 GPU for Normal Training, All are busy. Waiting for Free GPU ......，应该怎么解决啊

**Comment by tricktreat** [comment]
你好，检查一些GPU是否有足够的显存。一般需要24G显存。
