### ISSUE TITLE
which parameter that the threshold is? boundary_threshold ,cls_threshold  or entity_threshold ? please tell me the true. Thanks!

### ISSUE THREAD

**Issue by ekma000** [tricktreat/DiffusionNER#16]
In the paper, the razor's threshold=2.5 refers to which parameter's value? The code includes default values such as boundary_threshold = 0.0, cls_threshold = 0.0, entity_threshold = 0.0, but the paper does not specify which parameter actually needs to be modified.

**Comment by ekma000** [comment]
help!

**Comment by ekma000** [comment]
I need you help!

**Comment by tricktreat** [comment]
Apologies for the delay. In the paper, the term `threshold` refers to `entity_threshold`, for example:
https://github.com/tricktreat/DiffusionNER/blob/4727ebb87a5f04c448aca6463da2d03ed4f84f02/configs/ace2004.conf#L70

**Comment by tricktreat** [comment]
`boundary_threshold` and `cls_threshold` serve as more refined criteria, controlling the threshold values for boundary predictions and class predictions, respectively. You can distinguish these three thresholds via the following two lines of code:

`boundary_threshold` and `cls_threshold`:

https://github.com/tricktreat/DiffusionNER/blob/4727ebb87a5f04c448aca6463da2d03ed4f84f02/diffusionner/evaluator.py#L69

`entity_threshold`:

https://github.com/tricktreat/DiffusionNER/blob/4727ebb87a5f04c448aca6463da2d03ed4f84f02/diffusionner/evaluator.py#L71

**Comment by ekma000** [comment]
Thanks for sharing the information with me.
