### ISSUE TITLE
How to import diffusionner

### ISSUE THREAD

**Issue by Chenfeng1271** [tricktreat/DiffusionNER#2]
Hi, thank u for your work. When I run this code, I notice it has
`from diffusionner import input_reader`

I did not find this in the code. Is that a python package? or something I misunderstand.

**Comment by tricktreat** [comment]
Apologies for the oversight. The core code that was previously excluded by the .gitignore file has now been addressed, and I have successfully uploaded it.

**Comment by tomaarsen** [comment]
Appreciate it! I was a bit confused earlier already.
