### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by houyuchao** [tricktreat/DiffusionNER#21]
有没有遇到这个问题的，明明GPU空闲却无法训练呢？？
![image](https://github.com/tricktreat/DiffusionNER/assets/162104094/83982bbf-cfae-4d2d-9670-53533dd8374d)

**Comment by Eleven-Owl** [comment]
我也是 他没用cuda我不知道为什么

**Comment by tricktreat** [comment]
需要调整一下这里： https://github.com/tricktreat/DiffusionNER/blob/4727ebb87a5f04c448aca6463da2d03ed4f84f02/config_reader.py#L54
