### ISSUE TITLE
数据处理问题

### ISSUE THREAD

**Issue by zhangbosong-1024** [tricktreat/DiffusionNER#22]
你好，能提供对ace源数据处理的代码吗？处理xml类型的数据

**Comment by tricktreat** [comment]
请参考： https://github.com/yhcc/CNN_Nested_NER/tree/master/preprocess

**Comment by zhangbosong-1024** [comment]
> 请参考： https://github.com/yhcc/CNN_Nested_NER/tree/master/preprocess

好的，感谢！

**Comment by QianGuYiDi** [comment]
> 请参考： https://github.com/yhcc/CNN_Nested_NER/tree/master/preprocess

作者你好，请问tool文件夹中提供的ner2json.py程序和[context_convert.py程序是针对ACE数据集使用的预处理数据集代码吗？如果不是，是否使用您上面参考的连接中的预处理方法处理ace数据集。如果是，又该怎么使用？望不吝赐教，谢谢！
