### ISSUE TITLE
请问有能复现论文中ACE04数据集 F1score88.39的参数吗

### ISSUE THREAD

**Issue by Qlb6x** [tricktreat/DiffusionNER#3]
请问有能复现论文中ACE2004 F1score88.39的参数吗

**Comment by tricktreat** [comment]
你好，Google云盘满了，模型的checkpoint后面我会整理好上传到百度云盘上

**Comment by Qlb6x** [comment]
感谢

**Comment by tricktreat** [comment]
https://github.com/tricktreat/DiffusionNER/blob/main/configs/ace2004.conf

**Comment by Qlb6x** [comment]
感谢 我再调试看看
