### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by qinglongheu** [tricktreat/DiffusionNER#5]
zhmsra_types.json这个文件如何获取？

**Comment by moolean** [comment]
我看链接里是有的

**Comment by qinglongheu** [comment]
> 我看链接里是有的

老哥知道怎么将数据处理成他代码里面的json格式吗？我想用自己的数据跑一下

**Comment by tricktreat** [comment]
Hi. Please see [the latest commit](https://github.com/tricktreat/DiffusionNER/commit/a02e88da1d2987fab3f11093ac0c3d3e66b94da2)

+ `ner2json.py` : convert `conll` format (e.g. CoNLL03, OntoNotes) to JSON format.
+ `context_convert.py`: context-aware version. i.e., the left and right sentences are spliced to either side of the current sentence.

**Comment by liasddd-123** [comment]
这个预先训练的检查点怎么没办法下载

**Comment by tricktreat** [comment]
> 这个预先训练的检查点怎么没办法下载

Google云盘免费空间不够了，这几天我用百度云上传一下吧。

**Comment by liasddd-123** [comment]
好的感谢。我想问一下，就是对四个训练集训练完，再评估就可以看到现象了是吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tricktreat/DiffusionNER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月25日(星期五) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tricktreat/DiffusionNER] 数据集问题 (Issue #5)





  
这个预先训练的检查点怎么没办法下载
  
Google云盘免费空间不够了，这几天我用百度云上传一下吧。

**Comment by QianGuYiDi** [comment]
请问预训练检查点在哪里下载
