### ISSUE TITLE
Empty list for prediction during evaluation

### ISSUE THREAD

**Issue by imen185** [tricktreat/DiffusionNER#8]
Hello, 
Firstly, I would like to thank you for sharing your work.

I've been experimenting with the model but facing issues with inference – I keep getting empty lists for predictions. 
I've followed the README and installed dependencies correctly, but the problem persists. 
I'm seeking your guidance to understand what could be causing this issue and any specific configurations or test cases that might help.

Thank you in advance!

**Comment by tricktreat** [comment]
Hi. Thank you for your attention. Based on the information provided, it is difficult for me to help you. Can you provide more information? Including your training parameters, training log, evaluation parameters and evaluation log.
